<a href="https://colab.research.google.com/github/vidhya2432/Machine_Learning/blob/main/ML_2_Exp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Step 1: Import required libraries
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Step 2: Load the dataset
data = pd.read_csv("Iris.csv")

In [ ]:
# Step 3: Separate features and target
X = data.iloc[:, 1:-1].values   # Feature columns
y = data.iloc[:, -1].values    # Species column

In [ ]:
# Step 4: Encode class labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [ ]:
# Step 5: Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
    )

In [ ]:
# Step 6: Create k-NN classifier
knn = KNeighborsClassifier(n_neighbors=5)

In [ ]:
# Step 7: Train the model
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
# Step 8: Predict test data
y_pred = knn.predict(X_test)

In [ ]:
# Step 9: Evaluate the model
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n", cm)
print("Accuracy:", accuracy)

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0


In [ ]:
# Step 10: k-Fold Cross-Validation
cv_scores = cross_val_score(knn, X, y, cv=5)

print("Cross-validation scores:", cv_scores)
print("Average CV Accuracy:", cv_scores.mean())

Cross-validation scores: [0.96666667 1.         0.93333333 0.96666667 1.        ]
Average CV Accuracy: 0.9733333333333334
